/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SetData = IDL.Record({ 'weight' : IDL.Float64, 'reps' : IDL.Nat });
export const Exercise = IDL.Record({
  'primaryMuscleGroup' : IDL.Text,
  'recoveryTime' : IDL.Int,
  'name' : IDL.Text,
  'equipmentType' : IDL.Text,
  'demoUrl' : IDL.Text,
});
export const WorkoutExercise = IDL.Record({
  'setData' : IDL.Vec(SetData),
  'suggestedWeight' : IDL.Float64,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'exercise' : Exercise,
});
export const WorkoutWithNote = IDL.Record({
  'totalVolume' : IDL.Float64,
  'note' : IDL.Text,
  'exercises' : IDL.Vec(WorkoutExercise),
  'timestamp' : IDL.Int,
});
export const AppError = IDL.Variant({
  'userNotFound' : IDL.Text,
  'userProfileNotFound' : IDL.Text,
  'adminOnly' : IDL.Text,
  'internalError' : IDL.Text,
  'badArguments' : IDL.Text,
  'optimizationFailed' : IDL.Text,
  'unauthorized' : IDL.Text,
});
export const Result_7 = IDL.Variant({
  'ok' : WorkoutWithNote,
  'err' : AppError,
});
export const Result_6 = IDL.Variant({
  'ok' : IDL.Vec(Exercise),
  'err' : AppError,
});
export const TrainingFrequency = IDL.Variant({
  'threeDays' : IDL.Null,
  'fiveDays' : IDL.Null,
  'fourDays' : IDL.Null,
});
export const WeightUnit = IDL.Variant({ 'kg' : IDL.Null, 'lb' : IDL.Null });
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bodyweight' : IDL.Float64,
  'muscleGroupRestInterval' : IDL.Int,
  'trainingFrequency' : TrainingFrequency,
  'weightUnit' : WeightUnit,
  'darkMode' : IDL.Bool,
  'gender' : Gender,
  'restTime' : IDL.Int,
});
export const Result_3 = IDL.Variant({
  'ok' : IDL.Opt(UserProfile),
  'err' : AppError,
});
export const MuscleRecovery = IDL.Record({
  'lastTrained' : IDL.Int,
  'recoveryPercentage' : IDL.Float64,
});
export const Result_5 = IDL.Variant({
  'ok' : IDL.Record({
    'legs' : MuscleRecovery,
    'quads' : MuscleRecovery,
    'hamstrings' : MuscleRecovery,
    'glutes' : MuscleRecovery,
    'calves' : MuscleRecovery,
  }),
  'err' : AppError,
});
export const Result_4 = IDL.Variant({
  'ok' : IDL.Record({
    'calvesRecovery' : MuscleRecovery,
    'quadsRecovery' : MuscleRecovery,
    'hamstringsRecovery' : MuscleRecovery,
    'shoulders' : MuscleRecovery,
    'arms' : MuscleRecovery,
    'back' : MuscleRecovery,
    'core' : MuscleRecovery,
    'chest' : MuscleRecovery,
    'legs' : MuscleRecovery,
    'glutesRecovery' : MuscleRecovery,
  }),
  'err' : AppError,
});
export const Workout = IDL.Record({
  'totalVolume' : IDL.Float64,
  'exercises' : IDL.Vec(WorkoutExercise),
  'timestamp' : IDL.Int,
});
export const Result_2 = IDL.Variant({
  'ok' : IDL.Vec(Workout),
  'err' : AppError,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : AppError });
export const Result = IDL.Variant({ 'ok' : IDL.Float64, 'err' : AppError });

export const idlService = IDL.Service({
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'debugGetExerciseCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'generateFullBodyWorkout' : IDL.Func([], [Result_7], []),
  'generateLowerBodyWorkout' : IDL.Func([], [Result_7], []),
  'generateUpperBodyWorkout' : IDL.Func([], [Result_7], []),
  'getAlternativeExercises' : IDL.Func([IDL.Text], [Result_6], ['query']),
  'getCallerUserProfile' : IDL.Func([], [Result_3], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLegSubgroupRecovery' : IDL.Func([], [Result_5], ['query']),
  'getRecoveryState' : IDL.Func([], [Result_4], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [Result_3], ['query']),
  'getWorkoutHistory' : IDL.Func([], [Result_2], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isTestRecoveryModeEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [Result_1], []),
  'saveWorkout' : IDL.Func([Workout], [Result_1], []),
  'updateSuggestedWeightDuringSession' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Nat],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SetData = IDL.Record({ 'weight' : IDL.Float64, 'reps' : IDL.Nat });
  const Exercise = IDL.Record({
    'primaryMuscleGroup' : IDL.Text,
    'recoveryTime' : IDL.Int,
    'name' : IDL.Text,
    'equipmentType' : IDL.Text,
    'demoUrl' : IDL.Text,
  });
  const WorkoutExercise = IDL.Record({
    'setData' : IDL.Vec(SetData),
    'suggestedWeight' : IDL.Float64,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'exercise' : Exercise,
  });
  const WorkoutWithNote = IDL.Record({
    'totalVolume' : IDL.Float64,
    'note' : IDL.Text,
    'exercises' : IDL.Vec(WorkoutExercise),
    'timestamp' : IDL.Int,
  });
  const AppError = IDL.Variant({
    'userNotFound' : IDL.Text,
    'userProfileNotFound' : IDL.Text,
    'adminOnly' : IDL.Text,
    'internalError' : IDL.Text,
    'badArguments' : IDL.Text,
    'optimizationFailed' : IDL.Text,
    'unauthorized' : IDL.Text,
  });
  const Result_7 = IDL.Variant({ 'ok' : WorkoutWithNote, 'err' : AppError });
  const Result_6 = IDL.Variant({ 'ok' : IDL.Vec(Exercise), 'err' : AppError });
  const TrainingFrequency = IDL.Variant({
    'threeDays' : IDL.Null,
    'fiveDays' : IDL.Null,
    'fourDays' : IDL.Null,
  });
  const WeightUnit = IDL.Variant({ 'kg' : IDL.Null, 'lb' : IDL.Null });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bodyweight' : IDL.Float64,
    'muscleGroupRestInterval' : IDL.Int,
    'trainingFrequency' : TrainingFrequency,
    'weightUnit' : WeightUnit,
    'darkMode' : IDL.Bool,
    'gender' : Gender,
    'restTime' : IDL.Int,
  });
  const Result_3 = IDL.Variant({
    'ok' : IDL.Opt(UserProfile),
    'err' : AppError,
  });
  const MuscleRecovery = IDL.Record({
    'lastTrained' : IDL.Int,
    'recoveryPercentage' : IDL.Float64,
  });
  const Result_5 = IDL.Variant({
    'ok' : IDL.Record({
      'legs' : MuscleRecovery,
      'quads' : MuscleRecovery,
      'hamstrings' : MuscleRecovery,
      'glutes' : MuscleRecovery,
      'calves' : MuscleRecovery,
    }),
    'err' : AppError,
  });
  const Result_4 = IDL.Variant({
    'ok' : IDL.Record({
      'calvesRecovery' : MuscleRecovery,
      'quadsRecovery' : MuscleRecovery,
      'hamstringsRecovery' : MuscleRecovery,
      'shoulders' : MuscleRecovery,
      'arms' : MuscleRecovery,
      'back' : MuscleRecovery,
      'core' : MuscleRecovery,
      'chest' : MuscleRecovery,
      'legs' : MuscleRecovery,
      'glutesRecovery' : MuscleRecovery,
    }),
    'err' : AppError,
  });
  const Workout = IDL.Record({
    'totalVolume' : IDL.Float64,
    'exercises' : IDL.Vec(WorkoutExercise),
    'timestamp' : IDL.Int,
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Vec(Workout), 'err' : AppError });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : AppError });
  const Result = IDL.Variant({ 'ok' : IDL.Float64, 'err' : AppError });
  
  return IDL.Service({
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'debugGetExerciseCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'generateFullBodyWorkout' : IDL.Func([], [Result_7], []),
    'generateLowerBodyWorkout' : IDL.Func([], [Result_7], []),
    'generateUpperBodyWorkout' : IDL.Func([], [Result_7], []),
    'getAlternativeExercises' : IDL.Func([IDL.Text], [Result_6], ['query']),
    'getCallerUserProfile' : IDL.Func([], [Result_3], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLegSubgroupRecovery' : IDL.Func([], [Result_5], ['query']),
    'getRecoveryState' : IDL.Func([], [Result_4], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [Result_3], ['query']),
    'getWorkoutHistory' : IDL.Func([], [Result_2], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isTestRecoveryModeEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [Result_1], []),
    'saveWorkout' : IDL.Func([Workout], [Result_1], []),
    'updateSuggestedWeightDuringSession' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Nat],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };