/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppError = { 'userNotFound' : string } |
  { 'userProfileNotFound' : string } |
  { 'adminOnly' : string } |
  { 'internalError' : string } |
  { 'badArguments' : string } |
  { 'optimizationFailed' : string } |
  { 'unauthorized' : string };
export interface Exercise {
  'primaryMuscleGroup' : string,
  'recoveryTime' : bigint,
  'name' : string,
  'equipmentType' : string,
  'demoUrl' : string,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface MuscleRecovery {
  'lastTrained' : bigint,
  'recoveryPercentage' : number,
}
export type Result = { 'ok' : number } |
  { 'err' : AppError };
export type Result_1 = { 'ok' : null } |
  { 'err' : AppError };
export type Result_2 = { 'ok' : Array<Workout> } |
  { 'err' : AppError };
export type Result_3 = { 'ok' : [] | [UserProfile] } |
  { 'err' : AppError };
export type Result_4 = {
    'ok' : {
      'calvesRecovery' : MuscleRecovery,
      'quadsRecovery' : MuscleRecovery,
      'hamstringsRecovery' : MuscleRecovery,
      'shoulders' : MuscleRecovery,
      'arms' : MuscleRecovery,
      'back' : MuscleRecovery,
      'core' : MuscleRecovery,
      'chest' : MuscleRecovery,
      'legs' : MuscleRecovery,
      'glutesRecovery' : MuscleRecovery,
    }
  } |
  { 'err' : AppError };
export type Result_5 = {
    'ok' : {
      'legs' : MuscleRecovery,
      'quads' : MuscleRecovery,
      'hamstrings' : MuscleRecovery,
      'glutes' : MuscleRecovery,
      'calves' : MuscleRecovery,
    }
  } |
  { 'err' : AppError };
export type Result_6 = { 'ok' : Array<Exercise> } |
  { 'err' : AppError };
export type Result_7 = { 'ok' : WorkoutWithNote } |
  { 'err' : AppError };
export interface SetData { 'weight' : number, 'reps' : bigint }
export type TrainingFrequency = { 'threeDays' : null } |
  { 'fiveDays' : null } |
  { 'fourDays' : null };
export interface UserProfile {
  'bodyweight' : number,
  'muscleGroupRestInterval' : bigint,
  'trainingFrequency' : TrainingFrequency,
  'weightUnit' : WeightUnit,
  'darkMode' : boolean,
  'gender' : Gender,
  'restTime' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WeightUnit = { 'kg' : null } |
  { 'lb' : null };
export interface Workout {
  'totalVolume' : number,
  'exercises' : Array<WorkoutExercise>,
  'timestamp' : bigint,
}
export interface WorkoutExercise {
  'setData' : Array<SetData>,
  'suggestedWeight' : number,
  'reps' : bigint,
  'sets' : bigint,
  'exercise' : Exercise,
}
export interface WorkoutWithNote {
  'totalVolume' : number,
  'note' : string,
  'exercises' : Array<WorkoutExercise>,
  'timestamp' : bigint,
}
export interface _SERVICE {
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'debugGetExerciseCounts' : ActorMethod<[], Array<[string, bigint]>>,
  'generateFullBodyWorkout' : ActorMethod<[], Result_7>,
  'generateLowerBodyWorkout' : ActorMethod<[], Result_7>,
  'generateUpperBodyWorkout' : ActorMethod<[], Result_7>,
  'getAlternativeExercises' : ActorMethod<[string], Result_6>,
  'getCallerUserProfile' : ActorMethod<[], Result_3>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLegSubgroupRecovery' : ActorMethod<[], Result_5>,
  'getRecoveryState' : ActorMethod<[], Result_4>,
  'getUserProfile' : ActorMethod<[Principal], Result_3>,
  'getWorkoutHistory' : ActorMethod<[], Result_2>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isTestRecoveryModeEnabled' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], Result_1>,
  'saveWorkout' : ActorMethod<[Workout], Result_1>,
  'updateSuggestedWeightDuringSession' : ActorMethod<
    [string, number, bigint],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];