/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    primaryMuscleGroup: string;
    recoveryTime: bigint;
    name: string;
    equipmentType: string;
    demoUrl: string;
}
export interface WorkoutWithNote {
    totalVolume: number;
    note: string;
    exercises: Array<WorkoutExercise>;
    timestamp: bigint;
}
export type Result_2 = {
    __kind__: "ok";
    ok: RecoveryStateWithLegs;
} | {
    __kind__: "err";
    err: AppError;
};
export interface SetData {
    weight: number;
    reps: bigint;
}
export type AppError = {
    __kind__: "userNotFound";
    userNotFound: string;
} | {
    __kind__: "userProfileNotFound";
    userProfileNotFound: string;
} | {
    __kind__: "adminOnly";
    adminOnly: string;
} | {
    __kind__: "internalError";
    internalError: string;
} | {
    __kind__: "badArguments";
    badArguments: string;
} | {
    __kind__: "optimizationFailed";
    optimizationFailed: string;
} | {
    __kind__: "unauthorized";
    unauthorized: string;
};
export interface MuscleRecovery {
    lastTrained: bigint;
    recoveryPercentage: number;
}
export type Result_1 = {
    __kind__: "ok";
    ok: UserProfile | null;
} | {
    __kind__: "err";
    err: AppError;
};
export interface RecoveryStateWithLegs {
    calvesRecovery: MuscleRecovery;
    quadsRecovery: MuscleRecovery;
    hamstringsRecovery: MuscleRecovery;
    shoulders: MuscleRecovery;
    arms: MuscleRecovery;
    back: MuscleRecovery;
    core: MuscleRecovery;
    chest: MuscleRecovery;
    legs: MuscleRecovery;
    glutesRecovery: MuscleRecovery;
}
export type Result_4 = {
    __kind__: "ok";
    ok: WorkoutWithNote;
} | {
    __kind__: "err";
    err: AppError;
};
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: AppError;
};
export type Result_3 = {
    __kind__: "ok";
    ok: LegSubgroupRecovery;
} | {
    __kind__: "err";
    err: AppError;
};
export interface LegSubgroupRecovery {
    legs: MuscleRecovery;
    quads: MuscleRecovery;
    hamstrings: MuscleRecovery;
    glutes: MuscleRecovery;
    calves: MuscleRecovery;
}
export interface WorkoutExercise {
    setData: Array<SetData>;
    suggestedWeight: number;
    reps: bigint;
    sets: bigint;
    exercise: Exercise;
}
export interface UserProfile {
    bodyweight: number;
    muscleGroupRestInterval: bigint;
    trainingFrequency: TrainingFrequency;
    weightUnit: WeightUnit;
    darkMode: boolean;
    gender: Gender;
    restTime: bigint;
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum TrainingFrequency {
    threeDays = "threeDays",
    fiveDays = "fiveDays",
    fourDays = "fourDays"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WeightUnit {
    kg = "kg",
    lb = "lb"
}
export interface backendInterface {
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    debugGetExerciseCounts(): Promise<Array<[string, bigint]>>;
    generateLowerBodyWorkout(): Promise<Result_4>;
    getCallerUserProfile(): Promise<Result_1>;
    getCallerUserRole(): Promise<UserRole>;
    getLegSubgroupRecovery(): Promise<Result_3>;
    getRecoveryState(): Promise<Result_2>;
    getUserProfile(user: Principal): Promise<Result_1>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isTestRecoveryModeEnabled(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<Result>;
}
import type { AppError as _AppError, Gender as _Gender, LegSubgroupRecovery as _LegSubgroupRecovery, RecoveryStateWithLegs as _RecoveryStateWithLegs, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, TrainingFrequency as _TrainingFrequency, UserProfile as _UserProfile, UserRole as _UserRole, WeightUnit as _WeightUnit, WorkoutWithNote as _WorkoutWithNote } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async debugGetExerciseCounts(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.debugGetExerciseCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.debugGetExerciseCounts();
            return result;
        }
    }
    async generateLowerBodyWorkout(): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.generateLowerBodyWorkout();
                return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateLowerBodyWorkout();
            return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLegSubgroupRecovery(): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getLegSubgroupRecovery();
                return from_candid_Result_3_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLegSubgroupRecovery();
            return from_candid_Result_3_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecoveryState(): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecoveryState();
                return from_candid_Result_2_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecoveryState();
            return from_candid_Result_2_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isTestRecoveryModeEnabled(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isTestRecoveryModeEnabled();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isTestRecoveryModeEnabled();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_n32(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppError_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppError): AppError {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_TrainingFrequency_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrainingFrequency): TrainingFrequency {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_WeightUnit_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeightUnit): WeightUnit {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bodyweight: number;
    muscleGroupRestInterval: bigint;
    trainingFrequency: _TrainingFrequency;
    weightUnit: _WeightUnit;
    darkMode: boolean;
    gender: _Gender;
    restTime: bigint;
}): {
    bodyweight: number;
    muscleGroupRestInterval: bigint;
    trainingFrequency: TrainingFrequency;
    weightUnit: WeightUnit;
    darkMode: boolean;
    gender: Gender;
    restTime: bigint;
} {
    return {
        bodyweight: value.bodyweight,
        muscleGroupRestInterval: value.muscleGroupRestInterval,
        trainingFrequency: from_candid_TrainingFrequency_n12(_uploadFile, _downloadFile, value.trainingFrequency),
        weightUnit: from_candid_WeightUnit_n14(_uploadFile, _downloadFile, value.weightUnit),
        darkMode: value.darkMode,
        gender: from_candid_Gender_n16(_uploadFile, _downloadFile, value.gender),
        restTime: value.restTime
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    threeDays: null;
} | {
    fiveDays: null;
} | {
    fourDays: null;
}): TrainingFrequency {
    return "threeDays" in value ? TrainingFrequency.threeDays : "fiveDays" in value ? TrainingFrequency.fiveDays : "fourDays" in value ? TrainingFrequency.fourDays : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kg: null;
} | {
    lb: null;
}): WeightUnit {
    return "kg" in value ? WeightUnit.kg : "lb" in value ? WeightUnit.lb : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _LegSubgroupRecovery;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: LegSubgroupRecovery;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n5(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _RecoveryStateWithLegs;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: RecoveryStateWithLegs;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n5(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n5(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _WorkoutWithNote;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: WorkoutWithNote;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n5(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userNotFound: string;
} | {
    userProfileNotFound: string;
} | {
    adminOnly: string;
} | {
    internalError: string;
} | {
    badArguments: string;
} | {
    optimizationFailed: string;
} | {
    unauthorized: string;
}): {
    __kind__: "userNotFound";
    userNotFound: string;
} | {
    __kind__: "userProfileNotFound";
    userProfileNotFound: string;
} | {
    __kind__: "adminOnly";
    adminOnly: string;
} | {
    __kind__: "internalError";
    internalError: string;
} | {
    __kind__: "badArguments";
    badArguments: string;
} | {
    __kind__: "optimizationFailed";
    optimizationFailed: string;
} | {
    __kind__: "unauthorized";
    unauthorized: string;
} {
    return "userNotFound" in value ? {
        __kind__: "userNotFound",
        userNotFound: value.userNotFound
    } : "userProfileNotFound" in value ? {
        __kind__: "userProfileNotFound",
        userProfileNotFound: value.userProfileNotFound
    } : "adminOnly" in value ? {
        __kind__: "adminOnly",
        adminOnly: value.adminOnly
    } : "internalError" in value ? {
        __kind__: "internalError",
        internalError: value.internalError
    } : "badArguments" in value ? {
        __kind__: "badArguments",
        badArguments: value.badArguments
    } : "optimizationFailed" in value ? {
        __kind__: "optimizationFailed",
        optimizationFailed: value.optimizationFailed
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: [] | [_UserProfile];
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: UserProfile | null;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_opt_n9(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n5(_uploadFile, _downloadFile, value.err)
    } : value;
}
function to_candid_Gender_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_TrainingFrequency_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingFrequency): _TrainingFrequency {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_WeightUnit_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WeightUnit): _WeightUnit {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bodyweight: number;
    muscleGroupRestInterval: bigint;
    trainingFrequency: TrainingFrequency;
    weightUnit: WeightUnit;
    darkMode: boolean;
    gender: Gender;
    restTime: bigint;
}): {
    bodyweight: number;
    muscleGroupRestInterval: bigint;
    trainingFrequency: _TrainingFrequency;
    weightUnit: _WeightUnit;
    darkMode: boolean;
    gender: _Gender;
    restTime: bigint;
} {
    return {
        bodyweight: value.bodyweight,
        muscleGroupRestInterval: value.muscleGroupRestInterval,
        trainingFrequency: to_candid_TrainingFrequency_n26(_uploadFile, _downloadFile, value.trainingFrequency),
        weightUnit: to_candid_WeightUnit_n28(_uploadFile, _downloadFile, value.weightUnit),
        darkMode: value.darkMode,
        gender: to_candid_Gender_n30(_uploadFile, _downloadFile, value.gender),
        restTime: value.restTime
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingFrequency): {
    threeDays: null;
} | {
    fiveDays: null;
} | {
    fourDays: null;
} {
    return value == TrainingFrequency.threeDays ? {
        threeDays: null
    } : value == TrainingFrequency.fiveDays ? {
        fiveDays: null
    } : value == TrainingFrequency.fourDays ? {
        fourDays: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WeightUnit): {
    kg: null;
} | {
    lb: null;
} {
    return value == WeightUnit.kg ? {
        kg: null
    } : value == WeightUnit.lb ? {
        lb: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
